services:
  frontend:
    image: swr.cn-north-9.myhuaweicloud.com/linkseed/eap-frontend:latest
    ports:
      - "80:80"

  backend:
    image: swr.cn-north-9.myhuaweicloud.com/linkseed/eap-backend:latest
    volumes:
      - ./data:/app/data
    environment:
      - APP_LLM__BACKEND=llm
