services:
  frontend:
    image: swr.cn-north-9.myhuaweicloud.com/eap/frontend:latest
    ports:
      - "443:443"

  backend:
    image: swr.cn-north-9.myhuaweicloud.com/eap/backend:latest
    environment:
      - APP__BACKEND=llm
